apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appexpress
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: appexpress
    spec:
      containers:
      - name: sbapp
        image: sanchezbuitrago/appexpress:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"

       