apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: v1.app.test 
    http:
      paths:
      - backend:
          serviceName: appexpress-v1-svc
          servicePort: 80
  - host: v2.app.test
    http:
      paths:
      - backend:
          serviceName: apprest-v2-svc
          servicePort: 80